# Generated by Django 3.1.1 on 2020-09-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_auto_20200902_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_application',
            name='applied_by',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='leave_application',
            name='status',
            field=models.CharField(max_length=25),
        ),
    ]
